#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
#nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_DIY_IP $OPENSHIFT_REPO_DIR/diy > $OPENSHIFT_DIY_DIR/logs/server.log 2>&1 &
#nohup $OPENSHIFT_DATA_DIR/dlib-18.5/examples/build/server_http_ex > $OPENSHIFT_DIY_DIR/logs/server.log 2>&1 &
echo "starting.............."
export LD_LIBRARY_PATH=$OPENSHIFT_REPO_DIR/diy/App:$OPENSHIFT_REPO_DIR/diy/lib:$LD_LIBRARY_PATH
nohup $OPENSHIFT_REPO_DIR/diy/AppServer/AppServer -ip $OPENSHIFT_DIY_IP -port $OPENSHIFT_DIY_PORT  -maxconnections 1000 -maxcontentlength 1000000 -torrefreshpriod 300 -torrefreshnum 1 -proxyturn 0 -proxyrenewtrun 10 -torsnum 10 > $OPENSHIFT_DIY_DIR/logs/server.log 2>&1 &

